### ISSUE TITLE
pouet

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#11]
$ deckz init
17:34:52 deckz.cli Copying /nas/data/FORMATIONS/slides/templates/targets.yml to current directory
Traceback (most recent call last):
  File "/home/fmg/.virtualenvs/slides/bin/deckz", line 11, in <module>
    load_entry_point('deckz', 'console_scripts', 'deckz')()
  File "/nas/data/FORMATIONS/deckz/deckz/__main__.py", line 29, in main
    return handler(**vars(args))
  File "/nas/data/FORMATIONS/deckz/deckz/cli.py", line 176, in init
    shutil_copy(str(paths.template_targets), str(paths.working_dir))
  File "/home/fmg/opt/miniconda/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/fmg/opt/miniconda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/nas/data/FORMATIONS/slides/templates/targets.yml'

**Comment by m09** [comment]
t'as pas pull depuis slides j'pense

**Comment by nzmonzmp** [comment]
peut-être :-)
ça marche beaucoup mieux après le pull.
par contre j'ai été obligé de stash parce que mon poetry.lock avait changé.

je fais comment pour annuler la modif/stash/pouet/truc ?
