### ISSUE TITLE
j'aurais ptet pas du pull

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#19]
$ deckz 
```
Traceback (most recent call last):
  File "/home/fmg/.virtualenvs/slides/bin/deckz", line 11, in <module>
    load_entry_point('deckz', 'console_scripts', 'deckz')()
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/nas/data/FORMATIONS/deckz/deckz/__main__.py", line 7, in <module>
    from deckz.cli import commands
  File "/nas/data/FORMATIONS/deckz/deckz/cli/__init__.py", line 59, in <module>
    _import_module_and_submodules(__name__)
  File "/nas/data/FORMATIONS/deckz/deckz/cli/__init__.py", line 56, in _import_module_and_submodules
    _import_module_and_submodules(subpackage)
  File "/nas/data/FORMATIONS/deckz/deckz/cli/__init__.py", line 48, in _import_module_and_submodules
    module = import_module(package_name)
  File "/home/fmg/opt/miniconda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nas/data/FORMATIONS/deckz/deckz/cli/watch.py", line 8, in <module>
    from watchdog.events import FileSystemEvent
ModuleNotFoundError: No module named 'watchdog'

```

**Comment by m09** [comment]
poetry update

**Comment by nzmonzmp** [comment]
ah putain de memoire de poisson rouge !

**Comment by m09** [comment]
nan mais en même temps c'est ptet pas fou ce qu'on a fait, c'est instable entre deckz et ses deps, j'vais push un truc pour que ça soit toujours en sync :)

**Comment by m09** [comment]
Ok j'ai push une modif dans le git des slides où ça utilise le `deckz` de PyPI maintenant comme ça peut pas y avoir de décalage si tu fais pas un `poetry update`

**Comment by nzmonzmp** [comment]
top! merci!
