### ISSUE TITLE
MAJ de la poésie 3.5

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#45]
`$deckz run
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fmg/opt/miniconda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/fmg/opt/miniconda/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/builder.py", line 119, in _build
    self._write_main_latex(target, compile_type, latex_path)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/builder.py", line 151, in _write_main_latex
    print=compile_type is CompileType.PrintHandout,
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/builder.py", line 173, in _write_latex
    template = self._env.get_template(str(template_path.name))
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.tex.jinja2
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fmg/.virtualenvs/slides/bin/deckz", line 8, in <module>
    sys.exit(cli())
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/cli/__init__.py", line 110, in wrapper
    result = f(*args, **kwargs)
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/cli/run.py", line 33, in run
    target_whitelist=target_whitelist,
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/runner.py", line 24, in run
    build_print=build_print,
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/builder.py", line 44, in __init__
    self._build_all()
  File "/home/fmg/.virtualenvs/slides/lib/python3.7/site-packages/deckz/builder.py", line 63, in _build_all
    completed_processes = pool.starmap(self._build, to_compile)
  File "/home/fmg/opt/miniconda/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/fmg/opt/miniconda/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
jinja2.exceptions.TemplateNotFound: main.tex.jinja2
`

**Comment by m09** [comment]
t'as `git pull` et `poetry update` ou t'as `poetry update` sans `git pull` ? Si t'as pas pull c'est normal que ça marche pas (je mets à jour le pyproject.toml que quand j'ai mis à jour les fichiers nécessaires).

**Comment by m09** [comment]
en fait vaut mieux pas `poetry update` j'pense, vaut mieux juste `poetry install` et virer le lock si il dit que c'est pas à jour. On devrait sûrement remettre le lock maintenant qu'on a plus le symlink vers l'autre dossier d'ailleurs, comme ça toi t'utilises jamais poetry update et y a pas de souci.

**Comment by nzmonzmp** [comment]
tout de suite ça marche mieux.

Faut jamais sortir sans son pull...
